### ISSUE TITLE
Where get youtube api key

### ISSUE THREAD

**Issue by sharma-shray** [thecodophile/PlayTube#2]
We can get into the API in Google Clouid - APIs & Services - Enabled Api - CREATE CREDENTIALS, however the api key we get does not work.

**Comment by thecodophile** [comment]
To use this project, follow these steps:

1. Clone the repository.
2. Install the dependencies using npm install.
3. Now go to the Rapid API website. Type "youtube" and search, then among the all result choose the api named "YouTube", only "YouTube". That is a Freemium and Verified api.
3. Subscribe that api and copy the api key.
4. Create a .env file in the root directory and add your YouTube API key as REACT_APP_YOUTUBE_API_KEY=<your-api-key>.
5. Start the development server using npm start.
6. Open your web browser and navigate to http://localhost:3000.
